### ISSUE TITLE
sbt model-view server prototype

### ISSUE THREAD

**Issue by jsuereth** [sbt/sbt-remote-control#55]
This is a meta issue to track the progress of the sbt-server.  Here, we'll try to outline all the TODO items to get to the first prototype release.

- [x] Basic SocketServer handling  multiple clients
- [x] Initial single-queue-command-server-engine running requests.
- [x] Fire started/finished/value task events
- [x] Allow multiple clients to connect
- [x] Capture stdout/stderr for users
- [x] expose compatibility UIContext + plugin on the server.
- [x] Capture TestEvents and fire down socket
- [x] Capture compiler failure events.
- [x] Return possible completions of strings
- [x] Allow user to block for input or confirmation to the client running the most recent command request
- [x] Revamp integration test suite
- [x] Handle reload/set commands and BuildStructure change notifications.
- [x] Key discovery mechanisms
- [x] When listening to a TaskValue, also request it be executed.
- [x] Fragment terminal into its own project that depends on the client lib.
- [ ] Test on windows
- [ ] Test on OSX

Optional tasks (necessary before actual release)
- [ ] Use pure abstract API for serialization with bridges to play-json or whatever for now. #64
- [ ] "In-Process" Client API exposed for play #64
- [ ] Cancel Tasks being executed.  Including cancelling queued commands.
- [ ] Merge/Clear duplicate requests in queue..
- [ ] Pull in scala pickles lib once compile-time-only option enabled.
- [ ] Fix serialization registration for arbitrary value serialization. #64
- [x] Document internal architecture
- [x] Grab a ScopedKey by its string-form
- [x] Add autocompletion/JLine to terminal client
- [ ] Full set of tests.
- [ ] Scala REPL workaround (autocomplete/input)
